//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fbla_app.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fblaEntities : DbContext
    {
        public fblaEntities()
            : base("name=fblaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<ServiceAward> ServiceAwards { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentHour> StudentHours { get; set; }
        public virtual DbSet<vw_CommunityMembers> vw_CommunityMembers { get; set; }
        public virtual DbSet<vw_StudentHours> vw_StudentHours { get; set; }
    }
}
