//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fbla_app.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAward
    {
        public int Id { get; set; }
        public int CommunityId { get; set; }
        public string ServiceAwardName { get; set; }
        public int ServiceThreshhold { get; set; }
    }
}
