//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fbla_app.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CommunityMembers
    {
        public int CommunityId { get; set; }
        public string CommunityName { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string PrimaryUserId { get; set; }
        public string StudentCode { get; set; }
        public int Grade { get; set; }
    }
}
